### ISSUE TITLE
tried example.py - fails with missing authentication

### ISSUE THREAD

**Issue by ansash** [jpbede/pydiscovergy#32]
Hi - thanks in advance for the work !

Used the example to create my own test.py with eMail/Password/Serial from discovergy webpage.
Script is failing with following mesasge:
Traceback (most recent call last):
  File "/root/discovergy_export.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/discovergy_export.py", line 8, in main
    discovergy = Discovergy(email="USER@DOMAIN.de", password="12345suitcase")
TypeError: __init__() missing 1 required positional argument: 'authentication'

what am I missing ?

Best Regards !

**Comment by ansash** [comment]
nearly there - new error:
NameError: name 'discovergy' is not defined
however - this minor thing I'll lookup for myself.

Thanks a lot !
